#server.port=8080
## 应用名
#spring.application.name=alert-center
#
## 发布环境使用 /home/log
#application.log.folder=/home/logs
#
## 注册中心地址
#eureka.client.serviceUrl.defaultZone=${ewt360.eureka.client.serviceUrl:http://10.0.11.84:8762/eureka/}
## 使用ip注册到注册中心
#eureka.instance.prefer-ip-address=true
##服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
#eureka.instance.lease-expiration-duration-in-seconds=15
##服务刷新时间配置，每隔这个时间会主动心跳一次
#eureka.instance.lease-renewal-interval-in-seconds=5
##向注册中心拉取服务列表频率
#eureka.client.registryFetchIntervalSeconds=5
#
#
#feign.hystrix.enabled=true
#ribbon.ReadTimeout=5000
#ribbon.ConnectTimeout=1000


server:
  port: 8080
spring:
  application:
    name: consumer_service
application:
  log:
    folder: /home/logs
eureka:
  client:
    fetchRegistry: true
    #向注册中心拉取服务列表频率
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://10.0.11.84:8762/eureka/
  instance:
    # 使用ip注册到注册中心
    prefer-ip-address: true
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 5

feign:
  hystrix:
    enabled: true
ribbon:
  ReadTImeout: 3000
  ConnectTimeout: 1000